### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by paulharman** [tesla-android/issue-tracker#86] opened 2022-09-29 01:24 UTC
I've got a Huawei E3327 which is showing the blue light every 2 seconds to say it is connected to 3g(+) network, however Android is not showing an internet connection

**Comment by paulharman** [comment] 2022-09-29 09:16
Also my carlinkit is not being detected... wondering if its a USB hub issue?

**Comment by BroRidersMTL** [comment] 2022-09-29 15:13
Im having the same issue my carlinkit not detected but it is powered on

**Comment by paulharman** [comment] 2022-09-29 15:14
> Im having the same issue my carlinkit not detected but it is powered on

Is your LTE stick working?

**Comment by BroRidersMTL** [comment] 2022-09-29 15:20
Well i cut my service and waiting for a replacement but when i plugged it in it detected the device ill report back once i get replacement

**Comment by BroRidersMTL** [comment] 2022-09-30 01:01
I noticed this after playing around with it maybe its not normal says charging only?![image](https://user-images.githubusercontent.com/105889119/193167760-0f6824b0-7b8f-48c1-af6b-66db7b3f76aa.jpeg)

**Comment by BroRidersMTL** [comment] 2022-09-30 01:01
![image](https://user-images.githubusercontent.com/105889119/193167773-533b4fc2-8114-4a24-915e-444148eb5ca6.jpeg)

**Comment by BroRidersMTL** [comment] 2022-09-30 03:07
Carlinkit still not being detected up to sate did u get any luck?

**Comment by BroRidersMTL** [comment] 2022-09-30 03:46
> Also my carlinkit is not being detected... wondering if its a USB hub issue?

Figured it out take your pi4 plug ethernet and update autokit

**Comment by TroRon** [comment] 2022-09-30 04:31
> > Im having the same issue my carlinkit not detected but it is powered on
> 
> 
> 
> Is your LTE stick working?

I've the same problem. When i put my LTE Stick in my Computer everything works as expected.

Must be a Problem of Android in that case.

Hope it will be fixed soon :)

**Comment by mikegapinski** [comment] 2022-09-30 10:21
it needs to be at 2022.xx, 2021.08.31 is very old

**Comment by paulharman** [comment] 2022-09-30 10:24
> it needs to be at 2022.xx, 2021.08.31 is very old

Oh, I downloaded it from https://autokitcarplay.com/

**Comment by BroRidersMTL** [comment] 2022-09-30 13:13
Ya thanks but how come before it wasn't doing this with build 2 pi's

**Comment by rrlevy** [comment] 2022-10-02 12:52
I also have a problem with my LTE modem. No Internet on the new build, and I have internet on the old Linux build. Looks like some issue with Android

I use a HUAWEI E3272 modem.

**Comment by mikegapinski** [comment] 2022-10-02 13:03
Yes, it's a known issue with Huawei modem: https://twitter.com/mikegapinski/status/1576525188425981953

**Comment by rrlevy** [comment] 2022-10-02 14:49
Is the Alcatel modem working? I think I should get one then.

**Comment by mikegapinski** [comment] 2022-10-03 15:28
the alcatel one works since it does not rely on usbmodeswitch. The Huawei one will work in the next update, I've know what the problem is

**Comment by Cooker44** [comment] 2022-10-07 06:30
> the alcatel one works since it does not rely on usbmodeswitch. The Huawei one will work in the next update, I've know what the problem is

Thanks, Mike. Is the same fix going to allow iOS tether? This worked well for on two board setup and removes need for separate dongle and subscription thus lowering cost significantly.

**Comment by electricAntEater32** [comment] 2022-10-09 14:29
> Also my carlinkit is not being detected... wondering if its a USB hub issue?

I had to uninstall autokit app which comes with tesla-anderoid , download the latest & install. I also had to grant the android OS permission to use autokit app (perhaps this was real issue in the build?). Now carlinkit dongle is detected. However one more step, let tesla-android join your WAN internet access and rerun autokit, it will detect a newer version and offer to download it.  You can also make autokit search for new version in the settings menu.

**Comment by electricAntEater32** [comment] 2022-10-14 03:28
My Alcatel IK41UC(North America) stick is not detected by anderoid os. The stick works on my windows machine. No PIN was set yet. I do not see any options in Android  os settings app for configuring lte stick. Is there a tutorial I should be looking at?

**Comment by electricAntEater32** [comment] 2022-10-14 17:07
My Alcatel IK41UC(North America) is not working on Android. I see nowhere to set it up in Android either. Works on Windows.

**Comment by adrum** [comment] 2022-11-01 02:45
> > the alcatel one works since it does not rely on usbmodeswitch. The Huawei one will work in the next update, I've know what the problem is
> 
> Thanks, Mike. Is the same fix going to allow iOS tether? This worked well for on two board setup and removes need for separate dongle and subscription thus lowering cost significantly.

Is there something special that needs to be done to allow USB Tethering from an iPhone? Or is this not supported?

**Comment by mikegapinski** [comment] 2022-11-01 14:21
Please continue in the discussions section, it's hard for me to manage issues when they turn into a long offtopic thread.

@adrum Tethering from iOS is not supported at the moment

**Closed by mikegapinski** 2022-11-01 14:21 UTC
