### ISSUE TITLE
Internet works at Android but not in Car

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#185] opened 2022-12-01 19:17 UTC
I'm using the Alcatel IK41UC modem, and I guess it is the one with the correct firmware because it does get recognized by Tesla Android.

Although I can navigate on the Android system, download apps, use browser, etc, the car doesn't have Internet access.

I tested it also on my PC and the same thing happens. See video:

[![Watch the video](https://img.youtube.com/vi/whOtrOTR1-8/default.jpg)](https://youtu.be/whOtrOTR1-8)

**Comment by rrlevy** [comment] 2022-12-01 19:18
I'm on 2022.44.2

**Comment by mikegapinski** [comment] 2022-12-01 19:19
Can you connect your setup to the computer and send me the result of executing:

adb shell ifconfig -a
adb shell logcat 

Upload the logcat to pastebin, it's long

**Comment by mikegapinski** [comment] 2022-12-03 10:06
Pinging @rrlevy

**Comment by rrlevy** [comment] 2022-12-05 03:18
I tried doing that but I was having some issues:

- My office where the PC is located has very bad LTE signal, so I couldn't verify if the modem was running before running the commands
- After a while, the Raspberry would stop responding to adb commands. I was suspecting the PC USB port had not enough power for the Pi.

I could get a ifconfig though:

```
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope: Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1326 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1326 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:183556 TX bytes:183556
 
dummy0    Link encap:Ethernet  HWaddr 5e:0e:29:b2:59:2b
          inet6 addr: fe80::5c0e:29ff:feb2:592b/64 Scope: Link
          UP BROADCAST RUNNING NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 TX bytes:420
 
eth0      Link encap:Ethernet  HWaddr e4:5f:01:0e:42:40  Driver bcmgenet
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 TX bytes:0
 
ip_vti0   Link encap:UNSPEC
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 TX bytes:0
 
ip6_vti0  Link encap:UNSPEC
          NOARP  MTU:1332  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 TX bytes:0
 
ip6tnl0   Link encap:UNSPEC
          NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 TX bytes:0
 
eth1      Link encap:Ethernet  HWaddr 32:fd:78:bc:3a:12  Driver cdc_ether
          inet addr:192.168.1.103  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::9f71:9b0c:158e:f079/64 Scope: Link
          inet6 addr: 2804:18:84a:f243:7566:df95:c1e7:56e4/64 Scope: Global
          inet6 addr: 2804:18:84a:f243:be44:57f7:0:fa69/64 Scope: Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2520 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5003 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1941897 TX bytes:508359
 
wlan0     Link encap:Ethernet  HWaddr e4:5f:01:0e:42:41  Driver brcmfmac
          inet addr:9.9.0.1  Bcast:9.9.0.255  Mask:255.255.255.0
          inet6 addr: fe80::e65f:1ff:fe0e:4241/64 Scope: Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:32382 errors:0 dropped:0 overruns:0 frame:0
          TX packets:59061 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1508792 TX bytes:83708034
```

I also noticed:
- Although I couldn't get Internet access at my PC while on Tesla Android Wifi (replacing the car in a real world scenario), I could go to http://192.168.1.1/ at the PC and see the Modem configuration page
- I upgraded to 2022.45.1 and the same thing still happened


Does it have anything to do with my LTE provider using IPv6 addresss instead of IPv4? I think that might be going on.

**Comment by rrlevy** [comment] 2022-12-05 03:19
I will try to do further testing. I wanted to confirm the modem working on Android and not on PC on a location with good signal first on 2022.45.1 which I didn't do yet.

**Comment by mikegapinski** [comment] 2022-12-05 16:52
Everything looks fine on the ifconfig... Will try to reproduce, maybe it has something to do with the wireless hotspot starting before your modem manages to show up as a network interface(it happens only if after LTE is connected)...

If it was a more generic bug it would have happened for _all_ the users, but that does not seem to be the case.

One thing you can try:

Go to a space with decent connectivity, start your Tesla Android without the LTE stick, connect the car to the network and plug in the stick. Wait for the light to show up on the modem and test if you have internet. You should see connectivity both in Android and on Wi-Fi clients, I've tested this a lot of times with 45.1 when adding the support for USB tethering - you can connect and disconnect the internet many times and the connectivity will always work

**Comment by rrlevy** [comment] 2022-12-12 14:56
> Go to a space with decent connectivity, start your Tesla Android without the LTE stick, connect the car to the network and plug in the stick. Wait for the light to show up on the modem and test if you have internet. You should see connectivity both in Android and on Wi-Fi clients, I've tested this a lot of times with 45.1 when adding the support for USB tethering - you can connect and disconnect the internet many times and the connectivity will always work

I just did these steps and my car still has no connectivity, while the Android system does.

I have no idea what's going on.... For some reason the Tesla Android system will not route the car to the internet.

**Comment by inigoml** [comment] 2022-12-12 18:24
Routing is not working or NAT is not working or both at the same time. Since it's in hotspot mode, it should work out of the box....

**Comment by rrlevy** [comment] 2022-12-15 17:40
I suspect it might have something to do with the telecom operator. My operator is known for providing only IPv6 addresses when assigning a "valid IP" for some data plans.

How do I check if my modem is getting only a valid IPv6 instead of IPv4 address from the modem?

And @mikegapinski, will the routing rules at the Android system route correctly even if we are using IPv6?

**Comment by mikegapinski** [comment] 2022-12-15 17:49
@rrlevy Hmm, this is a very good tip! The routing for tethering probably does only ipv4... That is something I can actually reproduce with in a lab environment.

Before I do, do you have a different SIM card just to see if it's the case? My carrier is not v6 only and I would like to be certain that this is in fact the issue.

Fixing this might be tricky since I did not change anything about how tethering behaves - it's a stock behaviour from AOSP. There might be a feature flag for this somewhere, will take a look for you!

**Comment by rrlevy** [comment] 2022-12-15 18:27
I will try to find someone with a different SIM to borrow. All of my are from the same operator...

This is the only thing that I can think of that might be causing the issue. I know that if I plug an Ethernet cable into the Raspberry Pi, the car or computer connected to it WILL get internet access. And my cabled network is IPv4.

**Comment by mikegapinski** [comment] 2022-12-15 18:41
@rrlevy https://ipv6test.google.com open this website on a device with a SIM card from this operator,

Android seems to support IPV6 tethering only from the modem integrated with the device. Tesla Android uses Ethernet over USB for modems. that's why your carrier is not routed properly. (https://issuetracker.google.com/issues/36949085?pli=1)

**Comment by kobaje** [comment] 2023-01-11 11:58
Hi, I do have excatly the same problem with german Telekom provider. When I open https://ipv6test.google.com/ it says "you are already using IPv6". Will there be a workaround in the future? Regards Jens

**Comment by mikegapinski** [comment] 2023-01-11 12:01
@kobaje what carrier? I'm like 10km from the German border so I might just get a card and test it on a nearby SUC station.

There should be a workaround at some point, maybe Google already fixed this in Android 13...

**Comment by kobaje** [comment] 2023-01-11 12:04
It’s simply called „Telekom“. One of the three biggest in GermanyAm 11.01.2023 um 13:02 schrieb Michał Gapiński ***@***.***>:﻿
@kobaje what carrier? I'm like 10km from the German border so I might just get a card and test it on a nearby SUC station.
There should be a workaround at some point, maybe Google already fixed this in Android 13...

**Comment by mikegapinski** [comment] 2023-01-11 12:13
@kobaje 

Hmm, if Telekom.de would have given people issues I would have known by now... A lot of people use this network with Tesla Android. Just to confirm, you have the Huawei LTE stick, correct?

**Comment by kobaje** [comment] 2023-01-11 12:23
I use the Alcatel Stick. It delivers Internet to the Raspi and Tesla-Android. I updated Autokit over itAm 11.01.2023 um 13:13 schrieb Michał Gapiński ***@***.***>:﻿
@kobaje
Hmm, if Telekom.de would have given people issues I would have known by now... A lot of people use this network with Tesla Android. Just to confirm, you have the Huawei LTE stick, correct?

**Comment by mikegapinski** [comment] 2023-01-11 12:45
<img width="699" alt="image" src="https://user-images.githubusercontent.com/930055/211809505-cd16e7b3-8821-4e0e-8933-156eacfe9286.png">
It works fine on the Huawei stick... I'll see if there is any way around it. If you can still return the modem I would do it, that's the easiest solution honestly

**Comment by kobaje** [comment] 2023-01-11 12:58
Great! Thanks. Great project!Am 11.01.2023 um 13:45 schrieb Michał Gapiński ***@***.***>:﻿

It works fine on the Huawei stick... I'll see if there is any way around it

**Comment by rrlevy** [comment] 2023-01-11 15:52
I guess there is something different with the Alcatel Modem vs Huawai.

With the same SIM card, in Huwaei modem it will work but not Alcatel. Alcatel only has the internet working on the car.

Here are screenshots from yesterday in Huawei Modem:

![image](https://user-images.githubusercontent.com/14061585/211852351-62459689-94b6-4fc2-b54c-f9d7fbfbf81a.png)
![image](https://user-images.githubusercontent.com/14061585/211852387-bb638564-6dad-4bf9-83a2-bf47aa5f6804.png)

Both Android and Tesla works.

(However I'm having issues with the Huawei modem interfering with the carlinkit dongle and disabling it after a while. I still haven't solved that.)

**Comment by kobaje** [comment] 2023-01-23 11:07
I installed the latest update. Unfortunately this problem is still persistent. I‘ll try to get a huawei stick

**Comment by mikegapinski** [comment] 2023-01-23 11:08
@kobaje they are cheap on AliExpress if you don't mind the wait. Tethering from iOS and Android works now, you can also use it over usb.

**Comment by mikegapinski** [comment] 2023-01-23 13:16
I am going to close this for now, it has nothing to do with Tesla Android, it's just the USB dongle not playing ball

**Closed as completed by mikegapinski** 2023-01-23 13:16 UTC
