### ISSUE TITLE
Support for Alcatel IK40V

### ISSUE THREAD

**Issue by Bbuzby5656** [tesla-android/issue-tracker#144] opened 2022-11-08 22:54 UTC
@mikegapinski everythink working well - many thanks - but bought this LTE dongle - works fine in laptop, but despite lighting up correctly I can seem to get internet on the pi. Any advice? https://www.xsonly.com/collections/all-price-asc/products/alcatel-linkkey-usb-4g-lte-usb-dongle-mobile-broadband

**Comment by mikegapinski** [comment] 2022-11-09 08:31
Could you wait for 2022.45.1 this week and retest? I did some changes and your modem might get support from them.

BTW, it's not a UK specific modem, it's the older version of the European modem that I have at home. The newer model is IK41VE1(this one works out of the box) and yours is IK40V.

I thing we can get it running, I'll just buy it if logs won't be enough for me

**Comment by Bbuzby5656** [comment] 2022-11-09 22:50
No worries - many thanks

**Comment by mikegapinski** [comment] 2022-11-21 11:06
@Bbuzby5656 let me know if the modem works on 2022.45.1, if not, I'll ask you to capture some logs for me

**Comment by Bbuzby5656** [comment] 2022-11-21 19:13
Still nothing - how do I get logs?

**Comment by timdodge** [comment] 2022-11-21 20:34
I have the same modem and also can't get it to work with 2022.45.1. I'm also happy to help with logs, if needed.

Thanks, Tim

**Comment by Bbuzby5656** [comment] 2022-11-21 20:43
Thanks Tim!

**Comment by timdodge** [comment] 2022-11-21 23:17
Is there an alternative way to adb in, apart from USB C? neither of my PCs can supply enough current to boot my pi4. Perhaps network adb, or via an OTG cable to a USB B port, perhaps?

**Comment by mikegapinski** [comment] 2022-11-22 15:38
ADB only works over usb c, sadly.

**Comment by mikegapinski** [comment] 2022-11-22 16:14
Going back to the topic. 

Could someone with IK40V connect the modem to their Tesla Android setup and share the output of a few commands?

1. adb logcat
2. adb shell dmesg
3. adb shell lsusb
4. adb shell ifconfig -a

Please use pastebin.com for dmesg and logcat, the output is quite long

**Comment by timdodge** [comment] 2022-11-22 20:45
I found a cable/PC combination that works:

Dmesg: http://dpaste.com/BW262XJWK

$ cat lsusb.txt 
Bus 003 Device 001: ID 1d6b:0002
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 002: ID 2109:3431
Bus 002 Device 001: ID 1d6b:0003
Bus 001 Device 003: ID 1bbb:f000

cat ifconfig.txt 
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0 
          inet6 addr: ::1/128 Scope: Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:0 

dummy0    Link encap:Ethernet  HWaddr 56:ab:1c:bf:29:0b
          inet6 addr: fe80::54ab:1cff:febf:290b/64 Scope: Link
          UP BROADCAST RUNNING NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:420 

eth0      Link encap:Ethernet  HWaddr e4:5f:01:6c:0e:6c  Driver bcmgenet
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:0 

ip_vti0   Link encap:UNSPEC  
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:0 

ip6_vti0  Link encap:UNSPEC  
          NOARP  MTU:1332  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:0 

ip6tnl0   Link encap:UNSPEC  
          NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:0 

wlan0     Link encap:Ethernet  HWaddr e4:5f:01:6c:0e:6d  Driver brcmfmac
          inet addr:9.9.0.1  Bcast:9.9.0.255  Mask:255.255.255.0 
          inet6 addr: fe80::e65f:1ff:fe6c:e6d/64 Scope: Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:0 TX bytes:1028

**Comment by timdodge** [comment] 2022-11-22 20:51
The logcat is huge, but here is the end part containing the IK40V info: https://dpaste.com/9C2MJWNVD

**Comment by timdodge** [comment] 2022-11-22 20:58
I don't know whether this page is useful: https://forums.raspberrypi.com/viewtopic.php?t=234921
I'm not seeing a kernel panic, but I think getting usb-modeswitch working correctly is the key - that seems to be switching it from a storage device to a modem on my desktop.

**Comment by timdodge** [comment] 2022-11-22 21:03
Sorry more modeswitch info from logcat:
$ grep modesw *.txt
dmesg.txt:[    5.252807] init: Parsing file /vendor/etc/init/usb_modeswitch.rc...
dmesg.txt:[   54.930545] init: processing action (sys.usb_modem_trigger=true) from (/vendor/etc/init/usb_modeswitch.rc:9)
dmesg.txt:[   54.931973] init: starting service 'usb_modeswitch'...
dmesg.txt:[   55.032227] init: Service 'usb_modeswitch' (pid 1207) exited with status 0 oneshot service took 0.098000 seconds in background
dmesg.txt:[   55.032263] init: Sending signal 9 to service 'usb_modeswitch' (pid 1207) process group...
logcat.txt:01-01 00:00:05.252     0     0 I init    : Parsing file /vendor/etc/init/usb_modeswitch.rc...
logcat.txt:01-01 00:00:54.930     0     0 I init    : processing action (sys.usb_modem_trigger=true) from (/vendor/etc/init/usb_modeswitch.rc:9)
logcat.txt:01-01 00:00:54.931     0     0 I init    : starting service 'usb_modeswitch'...
logcat.txt:11-21 02:40:26.871  1207  1207 I usb_modeswitch: Look for target devices ...
logcat.txt:11-21 02:40:26.871  1207  1207 I usb_modeswitch:  No devices in target mode or class found
logcat.txt:11-21 02:40:26.871  1207  1207 I usb_modeswitch: Look for default devices ...
logcat.txt:11-21 02:40:26.871  1207  1207 I usb_modeswitch:  No devices in default mode found. Nothing to do. Bye!
logcat.txt:11-21 02:40:26.871  1207  1207 I usb_modeswitch: 
logcat.txt:01-01 00:00:55.032     0     0 I init    : Service 'usb_modeswitch' (pid 1207) exited with status 0 oneshot service took 0.098000 seconds in background
logcat.txt:01-01 00:00:55.032     0     0 I init    : Sending signal 9 to service 'usb_modeswitch' (pid 1207) process group...

**Comment by mikegapinski** [comment] 2022-11-22 21:04
right now Android is detecting your modem as a storage device, same thing happened with my Huawei modem before. Just need to add the modeswitch config :)

**Comment by mikegapinski** [comment] 2022-11-22 21:05
Thanks for the link to the raspi forum, it already has the config file that I need to use

**Comment by mikegapinski** [comment] 2022-11-22 22:05
Thats perfect, I'll include this config in the next version :D

**Comment by timdodge** [comment] 2022-11-22 22:20
Brilliant, thanks Mike.

**Comment by mikegapinski** [comment] 2023-01-22 17:05
@timdodge sorry it took so long. Time to close this issue: https://github.com/tesla-android/android-external-tesla-android-usb-networking-initialiser/commit/5def8670d5021462cc383f23db2e46d3a6a59e12

**Closed by mikegapinski** 2023-01-22 17:05 UTC

**Comment by timdodge** [comment] 2023-01-25 19:38
Thanks - I can confirm that 2023.4.2 is working with my IK40V.
